In [63]:
import pandas as pd
amazon_fires = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv", encoding = 'ISO-8859-1')
amazon_fires

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [64]:
# amz.head()

In [65]:
# amz.duplicated().sum()

In [66]:
# amz.rename(columns={'Unnamed: 0':'Amazon'}, inplace=True)

In [67]:
amazon_fires.rename(columns={'ano':'Year','mes':'month','estado':'state','numero':'number_of_fire','encontro':'date'}, inplace=True)
amazon_fires

      Year     month      state number_of_fire      date
0     1998   Janeiro       Acre        0 Fires  1/1/1998
1     1999   Janeiro       Acre        0 Fires  1/1/1999
2     2000   Janeiro       Acre        0 Fires  1/1/2000
3     2001   Janeiro       Acre        0 Fires  1/1/2001
4     2002   Janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  Dezembro  Tocantins            128  1/1/2012
6450  2013  Dezembro  Tocantins             85  1/1/2013
6451  2014  Dezembro  Tocantins            223  1/1/2014
6452  2015  Dezembro  Tocantins            373  1/1/2015
6453  2016  Dezembro  Tocantins            119  1/1/2016

[6454 rows x 5 columns]

In [68]:
# amz['month']= {'janeiro':'Jan','Fevereiro':'feb','Mar�o':'mar','Abril':'apr','Maio':'may','Junho':'jun','julho':'julay','Agosto':'aug','Setembro':'Jan','Outubro':'oct','Novembro':'nov','Dezembro':'des'}

In [69]:
# amz['month']

In [70]:
amazon_fires

      Year     month      state number_of_fire      date
0     1998   Janeiro       Acre        0 Fires  1/1/1998
1     1999   Janeiro       Acre        0 Fires  1/1/1999
2     2000   Janeiro       Acre        0 Fires  1/1/2000
3     2001   Janeiro       Acre        0 Fires  1/1/2001
4     2002   Janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  Dezembro  Tocantins            128  1/1/2012
6450  2013  Dezembro  Tocantins             85  1/1/2013
6451  2014  Dezembro  Tocantins            223  1/1/2014
6452  2015  Dezembro  Tocantins            373  1/1/2015
6453  2016  Dezembro  Tocantins            119  1/1/2016

[6454 rows x 5 columns]

In [71]:
# amz

In [72]:
amz = {
    'Janeiro': 'Jan', 'Fevereiro': 'Feb', 'Março': 'Mar',
    'Abril': 'Apr', 'Maio': 'May', 'Junho': 'Jun',
    'Julho': 'Jul', 'Agosto': 'Aug', 'Setembro': 'Sep',
    'Outubro': 'Oct', 'Novembro': 'Nov', 'Dezembro': 'Dec'
}

In [73]:
amz

{'Janeiro': 'Jan',
 'Fevereiro': 'Feb',
 'Março': 'Mar',
 'Abril': 'Apr',
 'Maio': 'May',
 'Junho': 'Jun',
 'Julho': 'Jul',
 'Agosto': 'Aug',
 'Setembro': 'Sep',
 'Outubro': 'Oct',
 'Novembro': 'Nov',
 'Dezembro': 'Dec'}

In [74]:
amz

{'Janeiro': 'Jan',
 'Fevereiro': 'Feb',
 'Março': 'Mar',
 'Abril': 'Apr',
 'Maio': 'May',
 'Junho': 'Jun',
 'Julho': 'Jul',
 'Agosto': 'Aug',
 'Setembro': 'Sep',
 'Outubro': 'Oct',
 'Novembro': 'Nov',
 'Dezembro': 'Dec'}

In [75]:
amazon_fires

      Year     month      state number_of_fire      date
0     1998   Janeiro       Acre        0 Fires  1/1/1998
1     1999   Janeiro       Acre        0 Fires  1/1/1999
2     2000   Janeiro       Acre        0 Fires  1/1/2000
3     2001   Janeiro       Acre        0 Fires  1/1/2001
4     2002   Janeiro       Acre        0 Fires  1/1/2002
...    ...       ...        ...            ...       ...
6449  2012  Dezembro  Tocantins            128  1/1/2012
6450  2013  Dezembro  Tocantins             85  1/1/2013
6451  2014  Dezembro  Tocantins            223  1/1/2014
6452  2015  Dezembro  Tocantins            373  1/1/2015
6453  2016  Dezembro  Tocantins            119  1/1/2016

[6454 rows x 5 columns]

In [76]:
amazon_fires['month']=amazon_fires['month'].map(amz)

In [77]:
amazon_fires['month'].unique()

<StringArray>
['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov',
 'Dec']
Length: 12, dtype: str

In [78]:
amazon_fires['month'].value_counts()

month
Jan    541
Feb    540
Mar    540
Apr    540
May    540
Jun    540
Jul    540
Aug    540
Sep    540
Oct    540
Nov    540
Dec    513
Name: count, dtype: int64

In [79]:
amazon_fires['month'].unique()

<StringArray>
['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov',
 'Dec']
Length: 12, dtype: str

In [80]:
amazon_fires

      Year month      state number_of_fire      date
0     1998   Jan       Acre        0 Fires  1/1/1998
1     1999   Jan       Acre        0 Fires  1/1/1999
2     2000   Jan       Acre        0 Fires  1/1/2000
3     2001   Jan       Acre        0 Fires  1/1/2001
4     2002   Jan       Acre        0 Fires  1/1/2002
...    ...   ...        ...            ...       ...
6449  2012   Dec  Tocantins            128  1/1/2012
6450  2013   Dec  Tocantins             85  1/1/2013
6451  2014   Dec  Tocantins            223  1/1/2014
6452  2015   Dec  Tocantins            373  1/1/2015
6453  2016   Dec  Tocantins            119  1/1/2016

[6454 rows x 5 columns]

In [81]:
amazon_fires.head()

   Year month state number_of_fire      date
0  1998   Jan  Acre        0 Fires  1/1/1998
1  1999   Jan  Acre        0 Fires  1/1/1999
2  2000   Jan  Acre        0 Fires  1/1/2000
3  2001   Jan  Acre        0 Fires  1/1/2001
4  2002   Jan  Acre        0 Fires  1/1/2002

In [82]:
amazon_fires.info()
amazon_fires.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            6454 non-null   int64
 1   month           6454 non-null   str
 2   state           6454 non-null   str
 3   number_of_fire  6322 non-null   str
 4   date            6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 252.2 KB

              Year
count  6454.000000
mean   2007.461729
std       5.746654
min    1998.000000
25%    2002.000000
50%    2007.000000
75%    2012.000000
max    2017.000000

In [83]:
amazon_fires.isnull().sum()

Year                0
month               0
state               0
number_of_fire    132
date                0
dtype: int64