In [18]:
import pandas as pd

In [19]:
import pandas as pd
df = pd.read_csv('Data-Analysis-Datasets/Datasets-Practice/amazon_fires.csv',encoding = 'ISO-8859-1', sep=',', na_values=[''], quotechar='"')
amazon_fires

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [20]:
print(df.head())
print(df.isnull().sum())
print(df.info())

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002
ano           0
mes           0
estado        0
numero      132
encontro      0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   str
 2   estado    6454 non-null   str
 3   numero    6322 non-null   str
 4   encontro  6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 252.2 KB
None

In [21]:
df = df.rename(columns={
    'ano': 'Year',
    'mes': 'Month',
    'estado': 'State',
    'numero': 'Number_of_Fires',
    'encontro': 'Date'
})

In [22]:
# ' Fires' word ko blank '' se replace kara hai
df['Number_of_Fires'] = df['Number_of_Fires'].astype(str).str.replace(' Fires', '')

# Ab isko number me convert kar do (agar kuch aur kachra hoga to 'coerce' usko NaN bana dega)
df['Number_of_Fires'] = pd.to_numeric(df['Number_of_Fires'], errors='coerce')

In [23]:
# Hame pata hai 132 jagah data missing hai, unhe hum 0 (zero) se bhar denge
df['Number_of_Fires'] = df['Number_of_Fires'].fillna(0)

In [24]:
# meri matlab data ke corrected dictionary
amz = {
    'Janeiro': 'Jan', 'Fevereiro': 'Feb', 'Março': 'Mar',
    'Abril': 'Apr', 'Maio': 'May', 'Junho': 'Jun',
    'Julho': 'Jul', 'Agosto': 'Aug', 'Setembro': 'Sep',
    'Outubro': 'Oct', 'Novembro': 'Nov', 'Dezembro': 'Dec'
}

# .map() use karke saare naam replace kar do
df['Month'] = df['Month'].map(amz)

In [25]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [26]:
df

      Year Month      State  Number_of_Fires       Date
0     1998   Jan       Acre              0.0 1998-01-01
1     1999   Jan       Acre              0.0 1999-01-01
2     2000   Jan       Acre              0.0 2000-01-01
3     2001   Jan       Acre              0.0 2001-01-01
4     2002   Jan       Acre              0.0 2002-01-01
...    ...   ...        ...              ...        ...
6449  2012   Dec  Tocantins            128.0 2012-01-01
6450  2013   Dec  Tocantins             85.0 2013-01-01
6451  2014   Dec  Tocantins            223.0 2014-01-01
6452  2015   Dec  Tocantins            373.0 2015-01-01
6453  2016   Dec  Tocantins            119.0 2016-01-01

[6454 rows x 5 columns]

In [27]:
print(df.head())
print(df.isnull().sum())
print(df.info())

   Year Month State  Number_of_Fires       Date
0  1998   Jan  Acre              0.0 1998-01-01
1  1999   Jan  Acre              0.0 1999-01-01
2  2000   Jan  Acre              0.0 2000-01-01
3  2001   Jan  Acre              0.0 2001-01-01
4  2002   Jan  Acre              0.0 2002-01-01
Year               0
Month              0
State              0
Number_of_Fires    0
Date               0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             6454 non-null   int64
 1   Month            6454 non-null   str
 2   State            6454 non-null   str
 3   Number_of_Fires  6454 non-null   float64
 4   Date             6454 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 252.2 KB
None

In [28]:
df['Month'] = df['Month'].astype(str).str.replace(' ', '')

In [29]:
df['Month'].unique()

<StringArray>
['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov',
 'Dec']
Length: 12, dtype: str

In [30]:
df

      Year Month      State  Number_of_Fires       Date
0     1998   Jan       Acre              0.0 1998-01-01
1     1999   Jan       Acre              0.0 1999-01-01
2     2000   Jan       Acre              0.0 2000-01-01
3     2001   Jan       Acre              0.0 2001-01-01
4     2002   Jan       Acre              0.0 2002-01-01
...    ...   ...        ...              ...        ...
6449  2012   Dec  Tocantins            128.0 2012-01-01
6450  2013   Dec  Tocantins             85.0 2013-01-01
6451  2014   Dec  Tocantins            223.0 2014-01-01
6452  2015   Dec  Tocantins            373.0 2015-01-01
6453  2016   Dec  Tocantins            119.0 2016-01-01

[6454 rows x 5 columns]