In [2]:
from os.path import join

import pandas as pd
from matplotlib.testing.jpl_units import day
from soupsieve.util import lower
hr_data = pd.read_csv('../../Data-Analysis-Datasets/Datasets-Practice/hr_data.csv', sep=',', na_values=[''], quotechar='"')
hr_data

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [3]:
import pandas as pd
w =winequalityN = pd.read_csv('../../Data-Analysis-Datasets/Datasets-Practice/winequalityN.csv', sep=',', na_values=[''], quotechar='"')
winequalityN

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
import pandas as pd
tips = tips = pd.read_csv('../../Data-Analysis-Datasets/Datasets-Practice/tips.csv', sep=',', na_values=[''], quotechar='"')
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [5]:
gender = tips.groupby('sex')

In [6]:
gender.groups

{'Female': [0, 4, 11, 14, 16, 18, 21, 22, 29, 32, 33, 37, 51, 52, 57, 66, 67, 71, 72, 73, 74, 82, 85, 92, 93, 94, 100, 101, 102, 103, 104, 109, 111, 114, 115, 117, 118, 119, 121, 124, 125, 127, 128, 131, 132, 133, 134, 135, 136, 137, 139, 140, 143, 144, 145, 146, 147, 155, 157, 158, 162, 164, 168, 169, 178, 186, 188, 191, 197, 198, 201, 202, 203, 205, 209, 213, 214, 215, 219, 221, 223, 225, 226, 229, 238, 240, 243], 'Male': [1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 15, 17, 19, 20, 23, 24, 25, 26, 27, 28, 30, 31, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 68, 69, 70, 75, 76, 77, 78, 79, 80, 81, 83, 84, 86, 87, 88, 89, 90, 91, 95, 96, 97, 98, 99, 105, 106, 107, 108, 110, 112, 113, 116, 120, 122, 123, 126, 129, 130, 138, 141, 142, 148, 149, 150, 151, 152, 153, 154, 156, 159, ...]}

In [7]:
male = gender.get_group('Male')

In [8]:
male

     Unnamed: 0  total_bill   tip   sex smoker  day    time  size
1             1       10.34  1.66  Male     No  Sun  Dinner     3
2             2       21.01  3.50  Male     No  Sun  Dinner     3
3             3       23.68  3.31  Male     No  Sun  Dinner     2
5             5       25.29  4.71  Male     No  Sun  Dinner     4
6             6        8.77  2.00  Male     No  Sun  Dinner     2
..          ...         ...   ...   ...    ...  ...     ...   ...
236         236       12.60  1.00  Male    Yes  Sat  Dinner     2
237         237       32.83  1.17  Male    Yes  Sat  Dinner     2
239         239       29.03  5.92  Male     No  Sat  Dinner     3
241         241       22.67  2.00  Male    Yes  Sat  Dinner     2
242         242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 8 columns]

In [9]:
female = gender.get_group('Female')['sex'].count()

In [10]:
female

np.int64(87)

In [11]:
# count of soker and non smokers in Tips

In [12]:
# smokers=tips.get_group('smoker')['smoker'].count()

In [13]:
s_count = tips.groupby('smoker')['smoker'].count()

In [14]:
s_count

smoker
No     151
Yes     93
Name: smoker, dtype: int64

In [15]:
# tip = tips.groupby('smoker')['tip'].count()

In [16]:
# tip

In [17]:
whr_p= hr_data.groupby('department')['number_project'].mean()

In [18]:
whr_p

department
IT             3.816626
RandD          3.853875
accounting     3.825293
hr             3.654939
management     3.860317
marketing      3.687646
product_mng    3.807095
sales          3.776329
support        3.803948
technical      3.877941
Name: number_project, dtype: float64

In [19]:
winequalityN=winequalityN.groupby('type')['pH'].mean()
winequalityN

type
red      3.310864
white    3.188203
Name: pH, dtype: float64

In [20]:
# female['tip'].max

In [21]:
dept=hr_data.groupby('department')
dept.get_group(('RandD'))[hr_data['salary']=='low'].count()

/var/folders/td/32c2rc793nb0d96_rh4bth0r0000gn/T/ipykernel_8335/1917086520.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dept.get_group(('RandD'))[hr_data['salary']=='low'].count()

employee_id              364
number_project           364
average_montly_hours     364
time_spend_company       364
Work_accident            364
left                     364
promotion_last_5years    364
department               364
salary                   364
dtype: int64

In [22]:
hr_data

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [23]:
day_gen=tips.groupby(['sex','day'])

In [24]:
day_gen.get_group(('Female','Fri'))

     Unnamed: 0  total_bill   tip     sex smoker  day    time  size
92           92        5.75  1.00  Female    Yes  Fri  Dinner     2
93           93       16.32  4.30  Female    Yes  Fri  Dinner     2
94           94       22.75  3.25  Female     No  Fri  Dinner     2
100         100       11.35  2.50  Female    Yes  Fri  Dinner     2
101         101       15.38  3.00  Female    Yes  Fri  Dinner     2
221         221       13.42  3.48  Female    Yes  Fri   Lunch     2
223         223       15.98  3.00  Female     No  Fri   Lunch     3
225         225       16.27  2.50  Female    Yes  Fri   Lunch     2
226         226       10.09  2.00  Female    Yes  Fri   Lunch     2

In [25]:
# Most highest tip given by male smoker = 10
# lowest bill of saturday by fimale
# count of emp whop are getting low salary and working in hr dept
# count of emp who are working in it and salary is high
# Avrage bill of male in saturady 's dinner

In [26]:
h = tips.groupby(['sex','smoker'])['tip'].max()

In [27]:
h

sex     smoker
Female  No         5.2
        Yes        6.5
Male    No         9.0
        Yes       10.0
Name: tip, dtype: float64

In [28]:
day=tips.groupby(['sex','day'])
day.get_group(('Female','Sat'))['total_bill'].min()

np.float64(3.07)

In [29]:
day

In [30]:
hr_data["department"].unique()

<StringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [31]:
count=hr_data.groupby(['department','salary'])
count.get_group(('hr','low')).count()

employee_id              335
number_project           335
average_montly_hours     335
time_spend_company       335
Work_accident            335
left                     335
promotion_last_5years    335
department               335
salary                   335
dtype: int64

In [32]:
count.get_group(('IT','high')).count()

employee_id              83
number_project           83
average_montly_hours     83
time_spend_company       83
Work_accident            83
left                     83
promotion_last_5years    83
department               83
salary                   83
dtype: int64

In [33]:
winequalityN

type
red      3.310864
white    3.188203
Name: pH, dtype: float64

In [34]:
w

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [35]:
# Concatitation of DataFrames

In [36]:
# it is a process of merging two or more dataframe

In [37]:
df = pd.DataFrame({'Loction':['Meerut','Delhi','Goa','home'],'Blood_group':['A+','B','C+','D+'],})

In [38]:
df

  Loction Blood_group
0  Meerut          A+
1   Delhi           B
2     Goa          C+
3    home          D+

In [39]:
# Type;
# fertical concatenation :
# syntax:
# pd.concat([var_1,var_2])
# 1) Horizantal concatention:
# syntax
# pd.concat([var_1,var_2],axis=1

In [40]:
# **join**:
# If we want to fatch the data from two different table simulataneosly we use join

In [41]:
# Type of joins:
# 1) inner --> matching record both the dataframes
# 2) outer  --> matching and unmatched records
# 3) left -->
# 4) right -->
# Syntax:
#pd.merge(var_!,var_2,on='common_col',how='type_of_join')

In [42]:
df['ID']=[105,106,104,103]

In [43]:
df

  Loction Blood_group   ID
0  Meerut          A+  105
1   Delhi           B  106
2     Goa          C+  104
3    home          D+  103

In [44]:
df

  Loction Blood_group   ID
0  Meerut          A+  105
1   Delhi           B  106
2     Goa          C+  104
3    home          D+  103

In [45]:
df_2=pd.DataFrame({'Name':['Uchia','Don','Munni','Uzumaki'],'ID':[105,106,104,103],'Salary':['20k','50k','70k','30k']})

In [46]:
df_2

      Name   ID Salary
0    Uchia  105    20k
1      Don  106    50k
2    Munni  104    70k
3  Uzumaki  103    30k

In [47]:
pd.merge(df,df_2,on='ID',how='inner')

  Loction Blood_group   ID     Name Salary
0  Meerut          A+  105    Uchia    20k
1   Delhi           B  106      Don    50k
2     Goa          C+  104    Munni    70k
3    home          D+  103  Uzumaki    30k

In [48]:
# Feature Engineering = it is a process of creating new columns based on existion columns

In [49]:
# syntax:
# var['col_name'] = new_value

In [50]:
import pandas as pd
titanic = pd.read_csv('../../Data-Analysis-Datasets/Datasets-Practice/titanic.csv', sep=',', na_values=[''], quotechar='"')
titanic

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [51]:
# count of famaly member present in each family
# excluding the family leader.

In [52]:
titanic['famaly_count_without_le'] = titanic['sibsp']+titanic['parch']

In [53]:
# count of famaly member paresent in each famaily

In [54]:
titanic['total_family_count']=titanic['famaly_count_without_le']+1
titanic

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,famaly_count_without_le,total_family_count
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0,1,2
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0,1,2
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0,0,1
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0,0,1
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0,0,1

In [55]:
# Fatch Family nanme from the whole name.
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,famaly_count_without_le,total_family_count
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4

In [56]:

# titanic['family_name'] = titanic['name'].str.split(',').str[0]

In [57]:
# titanic['Family_count'] = titanic.groupby('family_name')['family_name'].transform('count')

In [58]:
 # i = 'Allen, Miss. Elisabeth Walton'.split
#

In [59]:
# out = []
# for i in titanic['name']:
#     f_name = i.split_(',')[0]
#     out.append(f_name)
# out

In [64]:
titanic['family_name'] = titanic['name'].str.split().str[1]

In [65]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,famaly_count_without_le,total_family_count,family_name
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1,Miss.
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4,Master.
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Miss.
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Mr.
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Mrs.

In [66]:
titanic

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,famaly_count_without_le,total_family_count,family_name
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1,Miss.
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4,Master.
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Miss.
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Mr.
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Mrs.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0,1,2,Miss.
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0,1,2,Miss.
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0,0,1,Mr.
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0,0,1,Mr.
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0,0,1,Mr.